// Mocks generated by Mockito 5.4.6 from annotations
// in lame_weather/test/widget/locations_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:lame_weather/core/data/repositories/preferances_repository.dart'
    as _i8;
import 'package:lame_weather/core/domain/entities/location.dart' as _i7;
import 'package:lame_weather/features/location/domain/use_cases/get_location.dart'
    as _i3;
import 'package:lame_weather/features/location/domain/use_cases/get_location_suggestions.dart'
    as _i5;
import 'package:lame_weather/features/location/presentation/bloc/location_point_bloc.dart'
    as _i9;
import 'package:lame_weather/features/location/presentation/bloc/location_point_state.dart'
    as _i4;
import 'package:lame_weather/features/weather/data/repositories/weather_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeatherRepository_0 extends _i1.SmartFake
    implements _i2.WeatherRepository {
  _FakeWeatherRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCurrentLocationUseCase_1 extends _i1.SmartFake
    implements _i3.GetCurrentLocationUseCase {
  _FakeGetCurrentLocationUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationPointState_2 extends _i1.SmartFake
    implements _i4.LocationPointState {
  _FakeLocationPointState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetLocationSuggestionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocationSuggestionsUseCase extends _i1.Mock
    implements _i5.GetLocationSuggestionsUseCase {
  @override
  _i2.WeatherRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWeatherRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeWeatherRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WeatherRepository);

  @override
  set repository(_i2.WeatherRepository? value) => super.noSuchMethod(
    Invocation.setter(#repository, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<List<_i7.Location>> execute({required String? query}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#query: query}),
            returnValue: _i6.Future<List<_i7.Location>>.value(<_i7.Location>[]),
            returnValueForMissingStub: _i6.Future<List<_i7.Location>>.value(
              <_i7.Location>[],
            ),
          )
          as _i6.Future<List<_i7.Location>>);
}

/// A class which mocks [PreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesRepository extends _i1.Mock
    implements _i8.PreferencesRepository {
  @override
  List<_i7.Location> getSavedLocations() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocations, []),
            returnValue: <_i7.Location>[],
            returnValueForMissingStub: <_i7.Location>[],
          )
          as List<_i7.Location>);

  @override
  _i6.Future<void> saveLocations(List<_i7.Location>? locations) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocations, [locations]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [LocationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationBloc extends _i1.Mock implements _i9.LocationBloc {
  @override
  _i3.GetCurrentLocationUseCase get getCurrentLocationUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getCurrentLocationUseCase),
            returnValue: _FakeGetCurrentLocationUseCase_1(
              this,
              Invocation.getter(#getCurrentLocationUseCase),
            ),
            returnValueForMissingStub: _FakeGetCurrentLocationUseCase_1(
              this,
              Invocation.getter(#getCurrentLocationUseCase),
            ),
          )
          as _i3.GetCurrentLocationUseCase);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.LocationPointState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLocationPointState_2(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeLocationPointState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.LocationPointState);

  @override
  _i6.Stream<_i4.LocationPointState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.LocationPointState>.empty(),
            returnValueForMissingStub:
                _i6.Stream<_i4.LocationPointState>.empty(),
          )
          as _i6.Stream<_i4.LocationPointState>);

  @override
  void add(_i9.LocationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.LocationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.LocationPointState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.LocationEvent>(
    _i10.EventHandler<E, _i4.LocationPointState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i9.LocationEvent, _i4.LocationPointState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i9.LocationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i10.Change<_i4.LocationPointState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
